import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'

/**
 * Yellow Pad Pencil Log UI Theme
 * Defined in accordance with design_docs/UI_Mocks/DESIGN.md and UI.md
 */
export const scratchpadTheme = {
  dark: false,
  colors: {
    background: '#f6ebd0',
    'on-background': '#201b0b',
    surface: '#f6ebd0',
    'on-surface': '#1f1d17',
    'surface-dim': '#ebdca6',
    'surface-bright': '#fbf2d3',
    'surface-variant': '#ede2c7',
    'on-surface-variant': '#4a4639',
    'surface-container-lowest': '#fcf5dc',
    'surface-container-low': '#f4e7c5',
    'surface-container': '#f0e1b9',
    'surface-container-high': '#ebdcaf',
    'surface-container-highest': '#e8d89f',
    primary: '#1f1d18',
    'on-primary': '#fefbe8',
    'primary-container': '#2c2820',
    'on-primary-container': '#7a7360',
    'primary-fixed': '#e8e2d9',
    'primary-fixed-dim': '#cbc6be',
    'on-primary-fixed': '#1d1b16',
    'on-primary-fixed-variant': '#494640',
    secondary: '#575141',
    'on-secondary': '#ffffff',
    'secondary-container': '#eedea8',
    'on-secondary-container': '#4a4533',
    'secondary-fixed': '#ebe2cc',
    'secondary-fixed-dim': '#cfc6b1',
    'on-secondary-fixed': '#1f1b0e',
    'on-secondary-fixed-variant': '#4c4637',
    tertiary: '#040301',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#201d17',
    'on-tertiary-container': '#8a857c',
    'tertiary-fixed': '#e9e1d8',
    'tertiary-fixed-dim': '#ccc6bc',
    'on-tertiary-fixed': '#1e1b16',
    'on-tertiary-fixed-variant': '#4a463f',
    error: '#b91c1c',
    'on-error': '#ffffff',
    'error-container': '#fcdad7',
    'on-error-container': '#93000a',
    outline: '#786f58',
    'outline-variant': '#cdbe8d',
    'surface-tint': '#615e58',
    'inverse-surface': '#36301e',
    'inverse-on-surface': '#fbf0d5',
    'inverse-primary': '#cbc6be',
    info: '#575141',
    success: '#2e7d32',
    warning: '#ed6c02',
  },
}

export const scratchpadDarkTheme = {
  dark: true,
  colors: {
    background: '#1f1d18',
    'on-background': '#fbf0d5',
    surface: '#2c2820',
    'on-surface': '#fbf0d5',
    'surface-dim': '#201d17',
    'surface-bright': '#36301e',
    'surface-variant': '#4a4639',
    'on-surface-variant': '#cdbe8d',
    'surface-container-lowest': '#1f1d18',
    'surface-container-low': '#201d17',
    'surface-container': '#2c2820',
    'surface-container-high': '#36301e',
    'surface-container-highest': '#4a4639',
    primary: '#fbf0d5',
    'on-primary': '#1f1d18',
    'primary-container': '#2c2820',
    secondary: '#cfc6b1',
    'secondary-container': '#4c4637',
    tertiary: '#ccc6bc',
    'tertiary-container': '#201d17',
    error: '#ffb4ab',
    'error-container': '#93000a',
    outline: '#cdbe8d',
    'outline-variant': '#786f58',
    info: '#cfc6b1',
    success: '#81c784',
    warning: '#ffb74d',
    'inverse-surface': '#f6ebd0',
    'inverse-on-surface': '#1f1d17',
    'inverse-primary': '#1f1d18',
  },
}

export default createVuetify({
  components,
  directives,
  theme: {
    defaultTheme: 'scratchpad',
    themes: {
      scratchpad: scratchpadTheme,
      light: scratchpadTheme,
      scratchpadDark: scratchpadDarkTheme,
      dark: scratchpadDarkTheme,
    },
  },
})
